docs: add login step to tutorials
canonical/charmed-aether-sd-core pull request #49
Opened 2024-11-20 11:30 UTC by patriciareinoso

# Description

Now we have authentication for the NMS. This PR add the steps to login to the tutorials.
To retrieve the username and password we need to reveal the juju secret associated to the NMS application.

# Checklist:

- [ ] Documentation follows the [Canonical Documentation Style Guide](https://docs.ubuntu.com/styleguide/en)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2024-11-20 13:29 UTC, gatici approved these changes

2024-11-21 12:12 UTC, gruyaume requested changes

2024-11-22 10:49 UTC, patriciareinoso commented on docs/reference/user_management.md
> +The NMS allows the admin user to manage all users, including creating, changing passwords, and deleting accounts. Other users can manage all resources except user accounts.
there is only one admin user so I rephrased

2024-11-22 10:49 UTC, patriciareinoso commented on docs/reference/user_management.md
> +It is not possible to delete the admin user or change their password.
using the NMS we cannot. But if you directly reach the change password endpoint it's possible, so I hesitate what to write

2024-11-22 12:35 UTC, gruyaume approved these changes

2024-11-25 11:05 UTC, merged